### ISSUE TITLE
dados encriptados

### ISSUE THREAD

**Issue by michelmelo** [luismiguelprs/superplayer_extension#1]
se conseguir descodificar o <input type="hidden" id="preloadData" value="eyZxd...."> tens toda a informação que precisa para fazer downloads das musica, dados pessoas, passa para premium e etc :)
conseguir ver muita coisa ai que ajuda :+1:

**Comment by luismiguelprs** [comment]
Desculpe... não te entendi muito bem =/

**Comment by michelmelo** [comment]
na homepage do superplayer tem a isso:
 < input type="hidden" id="preloadData" value="eyZxd....">

**Comment by luismiguelprs** [comment]
uhm... eu vi esse campo mas não dei muita atenção. como tu fez para quebrar?

**Comment by luismiguelprs** [comment]
Pelo que vi é um base64

**Comment by michelmelo** [comment]
é tipo um base64

**Comment by luismiguelprs** [comment]
Pelo que vi é um JSON codificado em base64.
Mas não consegui imaginar alguma utilidade para esses dados, além de burlar o premium.
São os dados da conta e as playlist que aparecerão na página inicial.

ps.: Na minha extensão o premium já é burlado via JS.
